---

- name: Check Chrony Status
  ansible.builtin.command: chronyc tracking
  register: chrony_status
  failed_when: chrony_status.rc != 0
  changed_when: true

- name: Check firewalld status
  ansible.builtin.command: firewall-cmd --state
  register: firewalld_status
  failed_when: firewalld_status.rc != 0
  changed_when: true

- name: Check AWS Inspector status
  ansible.builtin.command: sudo /opt/aws/awsagent/bin/awsagent status
  register: aws_inspector_status
  failed_when: aws_inspector_status.rc != 0
  changed_when: true

- name: Check clamd status
  ansible.builtin.command: clamdscan --version
  register: clamd_status
  failed_when: clamd_status.rc != 0
  changed_when: true

- name: Check freshclam status
  ansible.builtin.command: freshclam
  register: freshclam_status
  failed_when: freshclam_status.rc != 0
  changed_when: true