---
# Role to install docker on the ec2 instances
- name: Disable selinux support
  ansible.posix.selinux:
    state: disabled

- name: Update yum repositories
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install docker on ec2 instance
  become: true
  become_user: root
  ansible.builtin.shell: |
    amazon-linux-extras install docker -y

- name: Start docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Create docker user
  ansible.builtin.user:
    name: docker
    createhome: no

- name: Add docker user to docker group
  ansible.builtin.group:
    name: ec2-user
    state: present
    members:
      - docker

- name: Enable changes after adding the new docker user
  ansible.builtin.shell: |
    newgrp docker
  notify:
    - Restart docker service
    - Check docker status

- name: Run docker hello world
  ansible.builtin.command: docker run hello-world
  register: docker_hello
  failed_when: docker_hello.rc != 0
  changed_when: true

- name: Enable selinux support
  ansible.posix.selinux:
    state: permissive
    policy: targeted
