# Install docker as the container daemon
# Install the kubernetes master asg
# Install the kubernetes node asg
# Prepare the instances with chrony, av, and other daemons

- name: Playbook for preparing an AWS EC2 instance
  hosts: all
  become: true
  become_user: ec2-user
  become_method: ansible.builtin.sudo

  roles:
    - role: install_docker
    - role: install_k8s_master
    # - role: install_k8s_node
    - role: prepare
