---
- name: Check docker status
  ansible.builtin.command: docker -v
  register: docker_status
  failed_when: docker_status.rc != 0
  changed_when: true

- name: Restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes
